create table roles (
    id bigint generated by default as identity primary key,
    name varchar(60) not null unique
);

create table users (
    id bigint generated by default as identity primary key,
    email varchar(190) not null unique,
    password_hash varchar(255) not null,
    name varchar(100) not null,
    phone varchar(40),
    status varchar(30) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    last_login_at timestamp
);

create table user_roles (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id),
    role_id bigint not null references roles(id),
    constraint uk_user_roles_user_role unique (user_id, role_id)
);

create table business_profiles (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id),
    company_name varchar(160),
    business_registration_no varchar(40),
    ceo_name varchar(80),
    business_type varchar(80),
    business_item varchar(80),
    tax_email varchar(190),
    credit_status varchar(30) not null
);

create table categories (
    id bigint generated by default as identity primary key,
    parent_id bigint references categories(id),
    name varchar(120) not null,
    slug varchar(160) not null unique,
    depth integer not null,
    sort_order integer not null,
    active boolean not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table products (
    id bigint generated by default as identity primary key,
    category_id bigint not null references categories(id),
    sku varchar(80) not null unique,
    name varchar(180) not null,
    summary varchar(500),
    description text,
    unit varchar(30),
    origin_country varchar(80),
    manufacturer varchar(120),
    custom_made boolean not null,
    lead_time_days_min integer,
    lead_time_days_max integer,
    status varchar(30) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table product_variants (
    id bigint generated by default as identity primary key,
    product_id bigint not null references products(id),
    variant_name varchar(180) not null,
    width_mm numeric(12, 2),
    length_mm numeric(12, 2),
    height_mm numeric(12, 2),
    thickness_mm numeric(12, 2),
    weight_kg numeric(12, 2),
    unit varchar(30),
    barcode varchar(80),
    status varchar(30) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table product_specs (
    id bigint generated by default as identity primary key,
    product_id bigint not null references products(id),
    variant_id bigint references product_variants(id),
    spec_key varchar(120) not null,
    spec_value varchar(500) not null,
    sort_order integer not null
);

create table product_media (
    id bigint generated by default as identity primary key,
    product_id bigint not null references products(id),
    variant_id bigint references product_variants(id),
    type varchar(40) not null,
    url varchar(600) not null,
    alt_text varchar(200),
    sort_order integer not null
);

create table product_relations (
    id bigint generated by default as identity primary key,
    source_product_id bigint not null references products(id),
    target_product_id bigint not null references products(id),
    relation_type varchar(40) not null,
    sort_order integer not null
);

create table price_books (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    effective_from date not null,
    effective_to date,
    default_book boolean not null,
    created_at timestamp not null
);

create table product_prices (
    id bigint generated by default as identity primary key,
    price_book_id bigint not null references price_books(id),
    product_id bigint not null references products(id),
    variant_id bigint not null references product_variants(id),
    sale_price integer not null,
    vat_policy varchar(40) not null,
    freight_policy varchar(40) not null,
    min_order_quantity numeric(12, 2) not null,
    price_note varchar(500),
    created_at timestamp not null,
    updated_at timestamp not null
);

create table loading_rules (
    id bigint generated by default as identity primary key,
    product_id bigint not null references products(id),
    variant_id bigint not null references product_variants(id),
    vehicle_type varchar(40) not null,
    load_quantity numeric(12, 2) not null,
    load_unit varchar(30) not null,
    pallet_quantity numeric(12, 2),
    pallet_weight_kg numeric(12, 2),
    note varchar(500)
);

create table delivery_options (
    id bigint generated by default as identity primary key,
    code varchar(60) not null unique,
    name varchar(120) not null,
    includes_freight boolean not null,
    description varchar(500),
    active boolean not null
);

create table freight_rate_rules (
    id bigint generated by default as identity primary key,
    origin_region varchar(80) not null,
    destination_region varchar(80) not null,
    vehicle_type varchar(40) not null,
    base_freight_amount integer not null,
    surcharge_rate numeric(8, 4),
    fuel_surcharge_rate numeric(8, 4),
    active boolean not null
);

create table freight_estimates (
    id bigint generated by default as identity primary key,
    product_id bigint references products(id),
    variant_id bigint references product_variants(id),
    quantity numeric(12, 2) not null,
    destination_address varchar(500) not null,
    vehicle_type varchar(40) not null,
    estimated_freight integer not null,
    unit_freight integer not null,
    calculation_snapshot text not null,
    created_at timestamp not null
);

create table carts (
    id bigint generated by default as identity primary key,
    user_id bigint references users(id),
    session_id varchar(120),
    cart_type varchar(30) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table cart_items (
    id bigint generated by default as identity primary key,
    cart_id bigint not null references carts(id),
    product_id bigint not null references products(id),
    variant_id bigint not null references product_variants(id),
    quantity numeric(12, 2) not null,
    delivery_option_id bigint references delivery_options(id),
    unit_price_snapshot integer,
    freight_estimate_snapshot text,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table quote_requests (
    id bigint generated by default as identity primary key,
    request_no varchar(40) not null unique,
    user_id bigint references users(id),
    company_name varchar(160) not null,
    contact_name varchar(80) not null,
    contact_phone varchar(40) not null,
    site_address varchar(500) not null,
    requested_delivery_date date,
    memo text,
    privacy_agreed boolean not null,
    status varchar(40) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table quote_items (
    id bigint generated by default as identity primary key,
    quote_request_id bigint not null references quote_requests(id),
    product_id bigint not null references products(id),
    variant_id bigint not null references product_variants(id),
    quantity numeric(12, 2) not null,
    unit_price integer,
    freight_amount integer,
    vat_amount integer,
    total_amount integer,
    note varchar(500)
);

create table consultations (
    id bigint generated by default as identity primary key,
    type varchar(40) not null,
    user_id bigint references users(id),
    product_id bigint references products(id),
    variant_id bigint references product_variants(id),
    contact_name varchar(80) not null,
    contact_phone varchar(40) not null,
    message text,
    status varchar(40) not null,
    assigned_to_id bigint references users(id),
    admin_memo text,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table search_logs (
    id bigint generated by default as identity primary key,
    user_id bigint references users(id),
    session_id varchar(120),
    keyword varchar(160) not null,
    result_count integer not null,
    created_at timestamp not null
);

create table audit_logs (
    id bigint generated by default as identity primary key,
    actor_id bigint references users(id),
    action varchar(120) not null,
    resource_type varchar(120) not null,
    resource_id varchar(120),
    ip_address varchar(80),
    user_agent varchar(400),
    created_at timestamp not null
);

create table counterparties (
    id bigint generated by default as identity primary key,
    company_name varchar(160) not null,
    business_registration_no varchar(40),
    contact_name varchar(80),
    contact_phone varchar(40),
    memo varchar(500),
    created_at timestamp not null,
    updated_at timestamp not null
);

create table credit_risk_notes (
    id bigint generated by default as identity primary key,
    counterparty_id bigint not null references counterparties(id),
    created_by_id bigint references users(id),
    note text not null
);

create index idx_products_category on products(category_id);
create index idx_product_variants_product on product_variants(product_id);
create index idx_search_logs_keyword_created on search_logs(keyword, created_at);
create index idx_quote_requests_status_created on quote_requests(status, created_at);
create index idx_consultations_status_created on consultations(status, created_at);
